version: '2'
services:
    encurtaurl-app:
        image: encurtaurl
        external_links:
            - encurtaurl-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/encurtaURL
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    encurtaurl-postgresql:
        extends:
            file: postgresql.yml
            service: encurtaurl-postgresql
